source("dh1.txt")
pdf("pdfs/rsplotdh1.pdf")
rsplot(z,xlab="dia. Blood Pressure",ylab='hdl Cholesterol',fac=2.5, cex.lab = 4)
dev.off()
source("tc1.txt")
pdf("pdfs/rsplottc1.pdf")
rsplot(z,xlab="Triglyceride",ylab='ldl Cholesterol',fac=2.5)
dev.off()
source("sb1.txt")
pdf("pdfs/rsplotsb1.pdf")
rsplot(z,xlab="sys. Blood Pressure",ylab='Body Mass Index (BMI)',fac=2.5, cex.lab = 4)
dev.off()
